version: '3.4'

services:
  runner:
    image: service:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_HOST: "mongo.local:27017"
      TEST_MONGO_HOST: "mongo.local:27017"

  server:
    image: service:production
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_HOST: "mongo.local:27017"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      default:
        aliases:
          - mongo.local
